name = "portfolio"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "51810e71-9e95-446c-82b7-6d42d0b3cc68"
